

name: Verificação de Build e Testes

on:
  [push, pull_request]

permissions:
    contents: write
    pull-requests: write

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  Build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Configurar Python
          uses: actions/setup-python@v5
          with:
           python-version: '3.x'
        - name: Install dependencies
          run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
        - name: Build PY
          run: |
            python -m py_compile main.py

  Testes:
    needs: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: Testes
        run: |
          pytest

  Deploy:
      runs-on: ubuntu-latest
      needs: [Build, Testes] # Só faz deploy após build e testes passarem
      if: |
        (
          startsWith(github.base_ref, 'main') ||
          startsWith(github.base_ref, 'sprint-')
        ) && 
        (
          github.event_name == 'pull_request'
        )
      steps:
        - uses: actions/checkout@v4
        
        - name: Configurar Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.x'
        
        - name: Deploy PY #Enviar arquivos para server
          run: |
            python -m py_compile main.py

  Aprovar:
    runs-on: ubuntu-latest
    needs: [Build, Testes, Deploy]
    steps:
        -   name: Aprovar PR
            uses: juliangruber/approve-pull-request-action@v1
            with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                number: ${{env.PR_NUMBER}}

  Mergear:
    runs-on: ubuntu-latest
    needs: [Build, Testes, Deploy, Aprovar]
    steps:
        -   name: Mergear PR
            uses: juliangruber/merge-pull-request-action@v1
            with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                number: ${{env.PR_NUMBER}}
                method: merge